In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(
    "../data/raw/Amazon Sale Report.csv",
    low_memory=False
)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 128975
Columns: 24

In [6]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [7]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Unnamed: 22']

In [8]:
#Dataset ka size
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 128975
Columns: 24

In [9]:
#Saare column names
print(df.columns.tolist())

['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

In [11]:
#Data ka overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

In [13]:
#Missing values check
missing = df.isnull().sum()
print(missing[missing > 0])

Courier Status       6872
currency             7795
Amount               7795
ship-city              33
ship-state             33
ship-postal-code       33
ship-country           33
promotion-ids       49153
fulfilled-by        89698
Unnamed: 22         49050
dtype: int64

In [14]:
#Duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [15]:
#Basic statistics
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
index,128975.0,NaN,NaN,NaN,64487.0,37232.019822,0.0,32243.5,64487.0,96730.5,128974.0
Order ID,128975,120378,403-4984515-8861958,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,128975,91,05-03-22,2085,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Status,128975,13,Shipped,77804,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fulfilment,128975,2,Amazon,89698,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sales Channel,128975,2,Amazon.in,128851,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship-service-level,128975,2,Expedited,88615,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Style,128975,1377,JNE3797,4224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SKU,128975,7195,JNE3797-KR-L,773,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,128975,9,Set,50284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,128975,11,M,22711,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASIN,128975,7190,B09SDXFFQ1,773,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Courier Status,122103,3,Shipped,109487,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Qty,128975.0,NaN,NaN,NaN,0.904431,0.313354,0.0,1.0,1.0,1.0,15.0
currency,121180,1,INR,121180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Amount,121180.0,NaN,NaN,NaN,648.561465,281.211687,0.0,449.0,605.0,788.0,5584.0
ship-city,128942,8955,BENGALURU,11217,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship-state,128942,69,MAHARASHTRA,22260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship-postal-code,128942.0,NaN,NaN,NaN,463966.236509,191476.764941,110001.0,382421.0,500033.0,600024.0,989898.0
ship-country,128942,1,IN,128942,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promotion-ids,79822,5787,IN Core Free Shipping 2015/04/08 23-48-5-108,46100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B2B,128975,2,False,128104,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fulfilled-by,39277,1,Easy Ship,39277,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 22,79925,1,False,79925,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Cleaning STARTS HERE

In [16]:
# Original data ko safe rakhne ke liye copy
clear_df = df.copy()
print("original rows:", df.shape[0])
print("cleandataset rows:", df.shape[1])

original rows: 128975
cleandataset rows: 24

In [20]:
# Unnecessary column remove karna
# Remove the extra empty column only if it exists
clear_df = clear_df.drop(columns=[col for col in ["Unnamed: 22"] if col in clear_df.columns])

print("Columns after removing unnecessary column:", clear_df.shape[1])

Columns after removing unnecessary column: 23

In [22]:
# Date ko proper date format mein convert karna
clear_df["Date"] = pd.to_datetime(
    clear_df["Date"],
    format="%m-%d-%y",
    errors="coerce"
)

print(clear_df["Date"].dtype)

datetime64[us]

In [23]:
print("Rows:", clear_df.shape[0])
print("Columns:", clear_df.shape[1])

print("\nMissing Values:")
print(clear_df.isnull().sum()[clear_df.isnull().sum() > 0])

print("\nDuplicate Rows:", clear_df.duplicated().sum())

Rows: 128975
Columns: 23

Missing Values:
Courier Status       6872
currency             7795
Amount               7795
ship-city              33
ship-state             33
ship-postal-code       33
ship-country           33
promotion-ids       49153
fulfilled-by        89698
dtype: int64

Duplicate Rows: 0

In [24]:
print(clear_df["Date"].dtype)

datetime64[us]

In [25]:
# Missing values ka percentage
missing = clear_df.isnull().sum()
missing_percent = (missing / len(clear_df)) * 100

missing_report = pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_percent.round(2)
})

missing_report = missing_report[missing_report["Missing Count"] > 0]
missing_report.sort_values("Missing %", ascending=False)

                  Missing Count  Missing %
fulfilled-by              89698      69.55
promotion-ids             49153      38.11
currency                   7795       6.04
Amount                     7795       6.04
Courier Status             6872       5.33
ship-state                   33       0.03
ship-city                    33       0.03
ship-country                 33       0.03
ship-postal-code             33       0.03

In [26]:
# Text columns se extra spaces remove karna

text_columns = clear_df.select_dtypes(include=["object"]).columns

for col in text_columns:
    clear_df[col] = clear_df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

print("Text columns cleaned successfully!")

C:\Users\niraj\AppData\Local\Temp\ipykernel_28036\2985985428.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = clear_df.select_dtypes(include=["object"]).columns

Text columns cleaned successfully!

In [27]:
# Amount ko numeric format mein convert karna

clear_df["Amount"] = pd.to_numeric(
    clear_df["Amount"],
    errors="coerce"
)

print("Amount datatype:", clear_df["Amount"].dtype)

Amount datatype: float64

In [28]:
# Missing currency ko INR se fill karna

clear_df["currency"] = clear_df["currency"].fillna("INR")

print("Currency cleaning completed!")

Currency cleaning completed!

In [29]:
# Missing location values ko Unknown se fill karna

for col in ["ship-city", "ship-state", "ship-country"]:
    clear_df[col] = clear_df[col].fillna("Unknown")

print("Location cleaning completed!")

Location cleaning completed!

In [30]:
# Missing courier status

clear_df["Courier Status"] = clear_df["Courier Status"].fillna("Unknown")

print("Courier Status cleaning completed!")

Courier Status cleaning completed!

In [31]:
# Missing promotion IDs ko identify karna

clear_df["promotion-ids"] = clear_df["promotion-ids"].fillna("No Promotion")

print("Promotion IDs cleaned successfully!")

Promotion IDs cleaned successfully!

In [32]:
# Missing Fulfilled By values ko handle karna

clear_df["fulfilled-by"] = clear_df["fulfilled-by"].fillna("Unknown")

print("Fulfilled By cleaned successfully!")

Fulfilled By cleaned successfully!

In [ ]:
#cleaning verify karo
print("Rows:", clear_df.shape[0])
print("Columns:", clear_df.shape[1])

print("\nRemaining Missing Values:")
print(clear_df.isnull().sum()[clear_df.isnull().sum() > 0])

print("\nDuplicate Rows:", clear_df.duplicated().sum())

Rows: 128975
Columns: 23

Remaining Missing Values:
Amount              7795
ship-postal-code      33
dtype: int64

Duplicate Rows: 0

In [34]:
clear_df.to_csv(
    "../data/cleaned/Amazon_Sale_Report_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!